### ISSUE TITLE
postcode_validation returns Bad Request error rather than FALSE

### ISSUE THREAD

**Issue by broganyoung** [ropensci/PostcodesioR#14]
This is happening for the postcode F93 HF23.
Obviously this is not a real postcode but when I use postcode_validation() to check if it is valid I get the following warnings message:

`Warning message:
In extract_results(r) : Bad Request (HTTP 400).`

I _think_ it happens with any 'postcode' with 'H' as the first letter of the second section of the postcode. I think it should be returning FALSE instead?

**Comment by erykwalczak** [comment]
I can't recreate this error. Calling `postcode_validation("F93 HF23")` returns `FALSE` as expected when I use it.
Have you checked your Internet connection? Which version of PostcodesioR are you using? I'm using 0.3.0.

**Comment by broganyoung** [comment]
Weird, I still get this error? Calling `postcode_validation("F93 HF23")` for me returns 
`Warning message: In extract_results(r) : Bad Request (HTTP 400).`.

Internet connection is all fine, I can validate any actual UK postcode fine. `postcode_validation("SW1A 2AA")` is `TRUE`. I can also call invalid postcodes fine. `postcode_validation("SW1B 2AA")` is `FALSE`.

But any postcode that has H at the start of the second section returns the HTTP 400 error? So I also get it for F93 HG22, or something like RAA HZ33. Anything where there is a space then a H. 

The version is 0.3.0, sorry should have said at the start.

**Comment by erykwalczak** [comment]
I still can't figure out what's causing this error as I can't reproduce it. Are you typing the postcode or loading it from a file/another source? Can you check the ASCII value of the string (e.g. by using http://asciivalue.com/). Maybe there's a [non-breaking space](https://en.wikipedia.org/wiki/Non-breaking_space) in the postcode.

**Comment by dave-lovell** [comment]
I've just reproduced this error - literally typed `postcode_validation("F93 HF23")` into the console and got a `NULL` return with the same warning message. 

This bug seems to occur with any (presumably invalid) postcode that contains a space followed by an "H" - I can literally replicate the bug with `postcode_validation(" H")`

Postcodes not containing the pattern " H" are returning logical values as expected.

I'm running Windows 10 and "R version 4.1.0 (2021-05-18)". 

Oh okay. I'll update R and see if it persists.

**Comment by dave-lovell** [comment]
I'm now reproducing this bug in R Version 4.1.1 (Kick Things), using package version 0.3.0

I've also been able to reproduce it outside of RStudio.

**Comment by erykwalczak** [comment]
I still could not reproduce the error. I wonder if there was an issue with the API, not with this wrapper, when you tested it. The API also returns _false_ as expected: https://api.postcodes.io/postcodes/F93HF23/validate

Here's what I tested:
> pc_clean <- gsub("[[:space:]]", "", "F93 HF23")
> postcode_validation(pc_clean)
[1] FALSE
> postcode_validation("F93 HF23")
[1] FALSE
> postcode_validation("SW19 1AH")
[1] TRUE
> postcode_validation(" H")
[1] FALSE`

**Comment by dave-lovell** [comment]
> I still could not reproduce the error. I wonder if there was an issue with the API, not with this wrapper, when you tested it. The API also returns _false_ as expected: https://api.postcodes.io/postcodes/F93HF23/validate

You were right; I've just reproduced the bug on my end without using `PostcodesioR`, so it's nothing to do with the package.

``` r
postcodesIo <- "https://api.postcodes.io"

brokenCode <- " H"
invalidCode <- "JFJFJ"
validCode <- "SW1A 0AA"

brokenPostcodeRequest <- paste(
  postcodesIo,
  "postcodes",
  brokenCode,
  "validate",
  sep = "/"
)

invalidPostcodeRequest <- paste(
  postcodesIo,
  "postcodes",
  invalidCode,
  "validate",
  sep = "/"
)

validPostcodeRequest <- paste(
  postcodesIo,
  "postcodes",
  validCode,
  "validate",
  sep = "/"
)

httr::GET(validPostcodeRequest)
#> Response [https://api.postcodes.io/postcodes/SW1A 0AA/validate]
#>   Date: 2021-10-18 14:47
#>   Status: 200
#>   Content-Type: application/json; charset=utf-8
#>   Size: 28 B

httr::GET(invalidPostcodeRequest)
#> Response [https://api.postcodes.io/postcodes/JFJFJ/validate]
#>   Date: 2021-10-18 14:47
#>   Status: 200
#>   Content-Type: application/json; charset=utf-8
#>   Size: 29 B

httr::GET(brokenPostcodeRequest)
#> Response [https://api.postcodes.io/postcodes/ H/validate]
#>   Date: 2021-10-18 14:47
#>   Status: 400
#>   Content-Type: text/html
#>   Size: 155 B
#> <html>
#> <head><title>400 Bad Request</title></head>
#> <body>
#> <center><h1>400 Bad Request</h1></center>
#> <hr><center>cloudflare</center>
#> </body>
#> </html>
```

<sup>Created on 2021-10-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by erykwalczak** [comment]
Thanks for the update. Please consider raising this issue with the API maker https://github.com/ideal-postcodes/postcodes.io

**Comment by cblanc** [comment]
Hi there! Our services are currently fronted by Cloudflare before they reach our application servers.

These requests don't reach our API. An unencoded space detected in a URL (i.e. it's not been translated to `%20`) will result in a 400 Bad Request - Cloudflare won't encode these on your behalf. I think the reason for this is that the ascii character for blank space indicates the end of the path [when you look at how a HTTP request is laid out](https://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html).

i.e. Cloudflare is expecting `https://api.postcodes.io/postcodes/SW1A%200AA/validate` instead of `https://api.postcodes.io/postcodes/SW1A 0AA/validate`

Thanks @erzk  for this fantastic package btw!

**Comment by erykwalczak** [comment]
Thanks for this comment @cblanc 
I think that you've identified the cause of these issues. Recently, I have also received an automatic warning message from CRAN about URL-related issue. I believe that I have solved it by using `utils::URLencode()`
